CREATE DATABASE QuanLyDoiBong
GO
USE QuanLyDoiBong
GO

CREATE TABLE TaiKhoan(
	id INT IDENTITY(1,1) PRIMARY KEY,
	TenDangNhap CHAR(100) UNIQUE NOT NULL,
	MatKhau	CHAR(255) NOT NULL,
	LoaiTK NVARCHAR(20) DEFAULT N'Nhân viên' NOT NULL, --Quản trị | Nhân viên
	NgayTao DATE DEFAULT GETDATE()
)
GO

CREATE TABLE NhaTaiTro(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaNhaTaiTro CHAR(100) UNIQUE NOT NULL,
	TenNhaTaiTro NVARCHAR(100) NOT NULL,
	NgayTaiTro DATE DEFAULT GETDATE()
)
GO

CREATE TABLE DoiTuyen(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaDoiTuyen CHAR(100) UNIQUE NOT NULL,
	TenDoiTuyen NVARCHAR(100) NOT NULL,
	MaNhaTaiTro CHAR(100) NOT NULL
)
GO

CREATE TABLE ThietBi(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaThietBi CHAR(100) UNIQUE NOT NULL,
	TenThietBi NVARCHAR(100) NOT NULL,
	SoLuong	INT NOT NULL,
	MaNhaTaiTro CHAR(100) NOT NULL
)
GO

CREATE TABLE CauThu(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaCauThu CHAR(100) UNIQUE NOT NULL,
	TenCauThu NVARCHAR(100) NOT NULL,
	NgaySinh DATE NOT NULL,
	DiaChi NVARCHAR(100) NOT NULL,
	SDT CHAR(11) NOT NULL,
	ViTri NVARCHAR(50) NOT NULL,
	SoAo INT NOT NULL,
	MaDoiTuyen CHAR(100) NOT NULL
)
GO

CREATE TABLE SucKhoe(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaCauThu CHAR(100) NOT NULL,
	NgayKham DATE NOT NULL,
	TinhTrang NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE Luong(
	id INT IDENTITY(1,1) PRIMARY KEY,
	MaCauThu CHAR(100) NOT NULL,
	ThangLuong INT NOT NULL,
	SoTien FLOAT NOT NULL
)
GO

-- TẠO KẾT NỐI KHÓA CHÍNH - NGOẠI
ALTER TABLE DoiTuyen ADD CONSTRAINT FK_DoiTuyen_NhaTaiTro FOREIGN KEY (MaNhaTaiTro) REFERENCES NhaTaiTro(MaNhaTaiTro)
ALTER TABLE ThietBi ADD CONSTRAINT FK_ThietBi_NhaTaiTro FOREIGN KEY (MaNhaTaiTro) REFERENCES NhaTaiTro(MaNhaTaiTro)
ALTER TABLE CauThu ADD CONSTRAINT FK_CauThu_DoiTuyen FOREIGN KEY (MaDoiTuyen) REFERENCES DoiTuyen(MaDoiTuyen)
ALTER TABLE SucKhoe ADD CONSTRAINT FK_SucKhoe_CauThu FOREIGN KEY (MaCauThu) REFERENCES CauThu(MaCauThu)
ALTER TABLE Luong ADD CONSTRAINT FK_Luong_CauThu FOREIGN KEY (MaCauThu) REFERENCES CauThu(MaCauThu)
GO

INSERT INTO TaiKhoan(TenDangNhap,MatKhau,LoaiTK) VALUES('admin', 'c4ca4238a0b923820dcc509a6f75849b', N'Quản trị');
SELECT * FROM dbo.TaiKhoan;